name: Spout-Test-Plugin
version: ${version}
main: spout.server.paper.testplugin.TestPlugin
description: Spout test plugin
author: Spout authors and contributors
api-version: ${apiversion}
load: STARTUP
bootstrapper: spout.server.paper.testplugin.TestPluginBootstrap
defaultPerm: FALSE
permissions:
dependencies:
