name: Spout-Paper-Test-Plugin
version: ${version}
main: spout.server.paper.testplugin.TestPlugin
description: Spout test plugin
author: Spout authors and contributors
api-version: ${apiversion}
load: STARTUP
bootstrapper: spout.server.paper.testplugin.TestPluginBootstrap
defaultPerm: FALSE
permissions:
dependencies:
namespaces:
  biome_makeover: Biome Makeover
  chinese_mythology_mashup: Chinese Mythology Mash-up
  maple_delight: Maple Delight
  minecraft_dungeons: Minecraft Dungeons
  more_barrel_variants: More Barrel Variants
  more_vanilla_shapes: More Vanilla Shapes
  quark: Quark
  red_portal: Red Portal
