# Builds the server JAR
name: build-paper-server
permissions:
  packages: write
on:
  push:
    branches: [ "master" ]
jobs:
  build-paper-server:
    # Only runs on master, and if the last commit does not start with [ci-skip]
    if: ${{ !contains(github.event.commits[0].message, '[ci-skip]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 25 ]
      fail-fast: true
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        continue-on-error: true
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Apply patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew :spout-paper:applyAllPatches --stacktrace
      - name: Build JAR
        run: ./gradlew :spout-paper:spout-server:createPaperclipJar --stacktrace
      - name: Rename and move JAR
        run: mv spout-paper/spout-server/build/libs/spout-paperclip-*.jar spout-$(basename spout-paper/spout-server/build/libs/spout-paperclip-*.jar | sed -E 's/^spout-paperclip-(.*)\.jar$/\1/').jar
      - name: Upload JAR
        uses: actions/upload-artifact@v7
        with:
          name: Spout server JAR
          path: spout-*.jar
          archive: false
